version: 2.1

jobs:
  run-script:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout

      - run:
          name: Preconfigure timezone
          command: |
            echo 'tzdata tzdata/Areas select Europe' | sudo debconf-set-selections
            echo 'tzdata tzdata/Zones/Europe select Paris' | sudo debconf-set-selections

      - run:
          name: Install Python and dependencies
          command: |
            sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata python3 python3-pip
            pip3 install -r requirements.txt

      - run:
          name: Run the RSS script
          command: python3 veille.py

      - persist_to_workspace:
          root: .
          paths:
            - index.html
            - flux/*.html

workflows:
  version: 2
  daily-run:
    triggers:
      - schedule:
          cron: "0 8 * * *" # Tous les jours à 08h00 UTC
          filters:
            branches:
              only:
                - main
    jobs:
      - run-script

  manual-run:
    jobs:
      - run-script
