name: Daily RSS Feed Generation

on:
  push: # Déclenche le workflow à chaque push sur la branche principale et active le check vert
    branches:
      - main
  schedule:
    - cron: '0 8 * * *' # Tous les jours à 08h00 UTC
  workflow_dispatch: # Permet un déclenchement manuel si nécessaire

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install -r requirements.txt

    - name: Run the RSS script
      run: python3 veille.py

    - name: Set date and time
      id: datetime
      run: echo "DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rss-generated-files-${{ env.DATETIME }}
        path: |
          index.html
          flux/*.html
